version: "3.3"
services:
  kafka:
    image: landoop/fast-data-dev
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "9092:9092"
      - "2181:2181"
      - "3030:3030"
    environment:
      - ADV_HOST=127.0.0.1